### ISSUE TITLE
ignore_provider_performance_dates

### ISSUE THREAD

**Issue by oHu812** [WorldVistA/popHealth#24]
Hello,

Best I can tell the design for this workaround was to stop looking at the time element in the provider performer. 

```
     <performer typeCode="PRF">
             <time>
                  <low value="20130101" />
                  <high value="20131231" />
             </time>
```

I cannot get this working and I have done everything short of dropping the DB and dropping the directory and reinstalling entirely. I reloaded the bundle, patients providers etc. Am I missing something. I do know that if I erase that element from the QRDA 1, it works as desired.

**Comment by grexican** [comment]
Is the problem with generating QRDA I documents and having multiple `effectiveTime`s in your output? If so, I have a monkeypatch that can help you. It's strange, because looking at the source code for health-data-standards, it actually generates more `effectiveTime` entries -- one per provider. And in the setup we have, we end up with 3 providers: <provider> Orphaned, <provider>, and Admin (in our case, the system itself).

Anyway if this is what you're having, try this monkeypatch.

Create /lib/hds/cat_1.rb and paste this:
```
module HealthDataStandards
  module Export
    class Cat1

      alias_method :original_export, :export

      # MONKEY PATCH: export with multiple provider_performances causes multiple iterations over providers which causes multiple effectiveTime outputs. For some reason, this is bad.
      def export(patient, measures, start_date, end_date, header=nil, r2_compatibility=false)
        ret = original_export(patient, measures, start_date, end_date, header=nil, r2_compatibility=false)

        begin
          doc = Nokogiri::XML(ret)
          doc.root.add_namespace_definition('cda', 'urn:hl7-org:v3')
          doc.root.add_namespace_definition('sdtc', 'urn:hl7-org:sdtc')

          effective_times = doc.xpath("/cda:ClinicalDocument/cda:documentationOf/cda:serviceEvent/cda:effectiveTime[position()>1]")
          effective_times.each { |et| et.remove }

          puts "Removing #{effective_times.length} yucky effectiveTimes"

          ret = doc.to_s
        rescue
          puts "Error #{$!}"
        end

        ret
      end
    end
  end
end
```

In /config/environment.rb, add: `require_relative '../lib/hds/cat_1.rb'`

And that's it. It will filter out those extra `effectiveTime`s that were generated by the official HDS library. With that, QRDA III and QRDA I tests are passing for me in Cypress.
